### ISSUE TITLE
Random error, is gone when rebuild

### ISSUE THREAD

**Issue by bedroesb** [ELIXIR-Belgium/elixir-toolkit-theme#47]
```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    nil can't be coerced into Integer
jekyll 3.9.0 | Error:  nil can't be coerced into Integer
Traceback (most recent call last):
        100: from /home/bedro/gems/bin/jekyll:23:in `<main>'
         99: from /home/bedro/gems/bin/jekyll:23:in `load'
         98: from /home/bedro/gems/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
         97: from /home/bedro/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
         96: from /home/bedro/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
         95: from /home/bedro/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
         94: from /home/bedro/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
         93: from /home/bedro/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
         92: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
         91: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
         90: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
         89: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
         88: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
         87: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
         86: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
         85: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:71:in `process'
         84: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:192:in `render'
         83: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:471:in `render_pages'
         82: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:471:in `each'
         81: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:472:in `block in render_pages'
         80: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/site.rb:479:in `render_regenerated'
         79: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:62:in `run'
         78: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:83:in `render_document'
         77: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `convert'
         76: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `reduce'
         75: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:99:in `each'
         74: from /home/bedro/gems/gems/jekyll-3.9.0/lib/jekyll/renderer.rb:101:in `block in convert'
         73: from /home/bedro/gems/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:119:in `convert'
         72: from /home/bedro/gems/gems/sass-3.7.4/lib/sass.rb:57:in `compile'
         71: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
         70: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/root_node.rb:20:in `render'
         69: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/root_node.rb:36:in `css_tree'
         68: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:10:in `visit'
         67: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:157:in `visit'
         66: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
         65: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
         64: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `block in visit'
         63: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
         62: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
         61: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
         60: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `visit_children'
         59: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `map'
         58: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
         57: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
         56: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
         55: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
         54: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
         53: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
         52: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
         51: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
         50: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:88:in `with_import'
         49: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
         48: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:88:in `block in with_import'
         47: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
         46: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `map'
         45: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
         44: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
         43: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
         42: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
         41: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
         40: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
         39: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
         38: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
         37: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:88:in `with_import'
         36: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
         35: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:88:in `block in with_import'
         34: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
         33: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `map'
         32: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
         31: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `visit'
         30: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:79:in `with_base'
         29: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:135:in `with_frame'
         28: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/stack.rb:79:in `block in with_base'
         27: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
         26: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/base.rb:36:in `visit'
         25: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/tree/visitors/perform.rb:478:in `visit_variable'
         24: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/node.rb:50:in `perform'
         23: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:129:in `_perform'
         22: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:129:in `map'
         21: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:129:in `each'
         20: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:129:in `each_with_index'
         19: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:129:in `each'
         18: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:129:in `block in _perform'
         17: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/funcall.rb:182:in `perform_arg'
         16: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/node.rb:50:in `perform'
         15: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:52:in `_perform'
         14: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:52:in `map'
         13: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:53:in `block in _perform'
         12: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/node.rb:50:in `perform'
         11: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:52:in `_perform'
         10: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:52:in `map'
          9: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:53:in `block in _perform'
          8: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/node.rb:50:in `perform'
          7: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:52:in `_perform'
          6: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:52:in `map'
          5: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/tree/map_literal.rb:54:in `block in _perform'
          4: from /usr/lib/ruby/2.7.0/set.rb:244:in `include?'
          3: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/value/number.rb:226:in `eql?'
          2: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/value/number.rb:403:in `basically_equal?'
          1: from /home/bedro/gems/gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `basically_equal?'
/home/bedro/gems/gems/sass-3.7.4/lib/sass/script/value/number.rb:409:in `-': nil can't be coerced into Integer (TypeError)
```

**Comment by bedroesb** [comment]
I seems like this is caused when the scss file is not yet rendered by Jekyll and it still contains the ```---``` frontmatter hyphens at the moment the SCSS parser uses the file. Not sure why this sometimes happens. Solution: rerunning the workflow

**Comment by bedroesb** [comment]
This error seems to be resolved in later Jekyll versions, but not with the latets GitHub pages gem (is lagging behind) -> solved when we would use GitHub Actions for deployment
